name: Create Release

on:
  push:
    branches:
      - main
      - master

jobs:
  create-release:
    # Sla over als het een bot-commit is
    if: ${{ !contains(github.event.head_commit.message, 'automatisch changelog') }}
    uses: bitmetric-bv/qlik-git-automation/.github/workflows/create-release.yml@main
    secrets: inherit